// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using wwimporters.infrastructure.Persistence;

#nullable disable

namespace wwimporters.infrastructure.Persistence.StoredProcedures.CustomMigrations
{
    [DbContext(typeof(WideWorldImportersContext))]
    [Migration("CreateStoredProcedures")]
    partial class CreateStoredProcedures
    {

    }
}
