version: "3"

services:
  db:
    container_name: sql-server-wwimporters
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    ports:
      - '1435:1433'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: 'SA__passw07d123'
    volumes:
      - 'drive/var/opt/mssql/data'
